name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby for CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        cd iosApp
        pod install

    - name: Build iOS app
      run: |
        cd iosApp
        xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/iosApp.xcarchive

    - name: Export .ipa
      run: |
        cd iosApp
        xcodebuild -exportArchive -archivePath build/iosApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/export

    - name: Upload .ipa artifact
      uses: actions/upload-artifact@v3
      with:
        name: iosApp-ipa
        path: iosApp/build/export/*.ipa 