name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: README.md